name: manuelsanchezcuadrado
favicon: null
layout_spectrum: 0.8536403081379831
typography_spectrum: 0.1285477359779179
title: welcome to my head
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8117551608011127
  lightness: 0.9296812051907182
  saturation: 0.2138220015913248
  rhythmicContrast: 0.4558241958729923
purpose: []
